import subprocess
import sys
import os
import platform
import re

def generate_requirements(script_path="main.py"):
    """Scans the script for imports and writes a requirements.txt file."""
    print("--- Scanning dependencies ---")
    with open(script_path, 'r') as f:
        content = f.read()

    # Regex to find standard top-level imports
    imports = re.findall(r"^(?:from|import)\s+([\w\d_]+)", content, re.MULTILINE)
    
    # Map of import names to PyPI package names
    mapping = {
        "PyQt6": "PyQt6",
        "numpy": "numpy",
        "qt_material": "qt-material",
    }
    
    found_packages = set()
    for imp in imports:
        if imp in mapping:
            found_packages.add(mapping[imp])
            # Ensure Multimedia is included if PyQt6 is used
            if imp == "PyQt6" and "QtMultimedia" in content:
                found_packages.add("PyQt6-Multimedia")

    with open("requirements.txt", "w") as f:
        f.write("# Automatically generated by build.py\n")
        for pkg in sorted(found_packages):
            # Using >= for forward compatibility with Python 3.14+
            f.write(f"{pkg}>=6.0.0\n" if "PyQt" in pkg else f"{pkg}\n")
    
    print(f"--- Generated requirements.txt with: {', '.join(found_packages)} ---")

def build_app():
    # 1. Prep
    generate_requirements()
    
    app_name = "AudioSorter"
    main_script = "main.py"
    icon_file = "audiosorter.png"
    
    # Detect separator
    sep = ";" if platform.system() == "Windows" else ":"
    
    # 2. Command Construction
    build_command = [
        "pyinstaller",
        "--noconfirm",
        "--onefile",
        "--windowed",
        f"--name={app_name}",
        f"--icon={icon_file}",
        "--add-data", f"AudioSorter.ui{sep}.",
        "--add-data", f"dark_teal.xml{sep}.",
        "--collect-submodules", "PyQt6.QtMultimedia",
        main_script
    ]

    # 3. Execution
    try:
        subprocess.run(build_command, check=True)
        print(f"\nSUCCESS: {app_name} built in 'dist/' folder.")
    except subprocess.CalledProcessError as e:
        print(f"\nERROR: Build failed. Ensure PyInstaller is installed.\n{e}")

if __name__ == "__main__":
    build_app()